[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
smartcontract = "GQkaiF2ajZcHkdxbPyDnpBpjscWrs4xAcpinETPDAqDt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
